import type { Metadata } from "next";

import "./globals.css";
import "@fontsource/fira-code";
import Sidebar from "@/components/Sidebar";
import TopHeader from "@/components/TopHeader";
import Footer from "@/components/Footer";
import { SidebarProvider } from "@/context/SidebarContext";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <SidebarProvider>
          <TopHeader />
          <div className="flex h-screen bg-vscodeBg text-vscodeText overflow-auto">
            <Sidebar />
            <main className="flex-grow p-6">{children}</main>
          </div>
          <Footer />
        </SidebarProvider>
      </body>
    </html>
  );
}
