import type { Metadata } from "next";

import "./globals.css";
import "@fontsource/fira-code";
import Sidebar from "@/components/Sidebar";
import TopHeader from "@/components/TopHeader";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <TopHeader />
        <div className="flex h-screen bg-vscodeBg text-vscodeText">
          <Sidebar />
            <main className="flex-grow p-6">{children}</main>
        </div>
      </body>
    </html>
  );
}
